---
version: '3'
services:

  ws3500:
    build: ./
    image: ws3500
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 192.168.1.1:8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
